dist: xenial
language: python
python: 3.6
sudo: required

matrix:
    include:
    ##############
    # GCC
    ##############
    - os: linux
      compiler: gcc
      env: GCC_VERSION=8
        - CC=gcc-8
        - CXX=g++-8
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: ['g++-8', 'ninja-build']

    ##############
    # CLANG
    ##############
    - os: linux
      compiler: clang
      env: CLANG_VERSION=7
        - CC=clang-7
        - CXX=clang++-7
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial
            - llvm-toolchain-trusty-7
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: ['clang-7', 'libc++-7-dev', 'libc++abi-7-dev', 'ninja-build']

    ##############
    # OSX / APPLECLANG (Python download failing)
    ##############
    #- os: osx
    #  osx_image: xcode10.1
    #  env:
    #    - CXX=clang
    #    - OSX=1

before_install:
  - echo "Before install"
  - |
    git submodule init
    git submodule update
  - |
    if [ "${CLANG_VERSION}" == "7" ]; then
      export CXXFLAGS="-stdlib=libc++"
    fi

install:
  - mkdir -p build
  - pip install meson

script:
  - which $CXX
  - $CXX --version
  - meson -Dcpp_std=c++11  c++11
  - meson -Dcpp_std=c++17  c++17
  - meson -Dcpp_std=c++2a  c++2a
  - ninja -C c++11 test
  - ninja -C c++17 test
  - ninja -C c++2a test
